feat: Add support for rewriting imports in declaration files
tylerbutler/tsc-multi pull request #1
Opened 2023-12-08 16:55 UTC by tylerbutler

This PR adds minimal support for rewriting imports in declaration (.d.ts) files. To enable this add `rewriteDtsImports: true` to the tsc-multi target config. If `rewriteDtsImports` is false or omitted, behavior should match exactly what it is today without this feature.

Features you may want or expect but are NOT included:

- Declaration files are not renamed. I tried, but every time I changed something I broke something else. Incorporating that will take more time than I have to spend right now.
- The sourcemap references are not rewritten. This is probably relatively easy to add, but again when I tried, I broke other things.

2023-12-08 17:41 UTC, tylerbutler commented on src/transformers/rewriteDtsImport.ts
> +    }
This might not be needed any more. I think it's from an earlier iteration before I figured out how to add a setting to the config to control whether declarations are rewritten or not. The original approach was to special case the .mjs file extension/ignore .cjs.

But I don't intend to remove this since it's been there for all my testing.

2023-12-08 18:49 UTC, Josmithr commented
This PR appears to be targeting main on your fork, rather than upstream main. Was this intentional?

2023-12-08 18:52 UTC, Josmithr commented on src/worker/worker.ts
> +                rewriteDtsImports: this.data.target
We already know `this.data.target.rewriteDtsImports` is false, given that we're in the else case of the ternary. This can probably be simplified to just `false`

2023-12-08 18:54 UTC, Josmithr commented on src/config.ts
> +  rewriteDtsImports: optional(boolean()),
This controls rewriting of both `d.ts` imports _and_ `ts` imports, right? Wondering if a more general property name would be appropriate.

2023-12-08 18:59 UTC, Josmithr commented on src/transformers/rewriteDtsImport.ts
> +export function createRewriteDtsImportTransformer(
Docs explaining all of what this is intended to do would be helpful for reviewers

2023-12-08 20:39 UTC, tylerbutler commented
> This PR appears to be targeting main on your fork, rather than upstream main. Was this intentional?

Yes. It's not anywhere near ready to open as an upstream change. There are no tests, plus it's lacking features that would be expected in a "real implementation." I'd love to do that extra work, but I don't have the time now.

2023-12-19 00:49 UTC, jason-ha commented on src/worker/worker.ts
> +   * Rewrites an output file path based on its extension. If ignoreDts is true, then paths to DSTS files will not be
"DSTS files" - is that a term? Otherwise, say `.d.ts` files?

2023-12-19 00:51 UTC, jason-ha commented on src/worker/worker.ts
> +    // Exclude files in node_modules
Okay. But why? Why doesn't the JS case deal with `node_modules`?

2023-12-19 00:55 UTC, jason-ha commented on src/config.ts
> +  rewriteDtsImports: optional(boolean()),
Seems like a proper config would specify a string like extname does and allow handling of both .d.cts and .d.mts.

2023-12-19 01:29 UTC, jason-ha commented on src/worker/worker.ts
> +                system: this.system,
This seems suspect. Why is it .data.target and need a cast?
extname in line above uses .data and has no cast.

2023-12-19 02:24 UTC, tylerbutler commented on src/worker/worker.ts
> +    // Exclude files in node_modules
Refactored and cleaned up in latest.

2023-12-19 02:26 UTC, tylerbutler commented on src/worker/worker.ts
> +                system: this.system,
I don't understand how the config options are passed. If you look at the worker invocation it calls a function "loadWorkerData" that appears to load from stdin?? But I can't figure out what writes to stdout that it's reading from. In the latest I extract the value from `.target` and set it directly on `.data`. But I don't know why it isn't there in the first place?

2023-12-19 02:27 UTC, tylerbutler commented on src/config.ts
> +  rewriteDtsImports: optional(boolean()),
Refactored the latest to use a setting dtsExtName instead of the boolean.

2023-12-19 08:34 UTC, jason-ha commented on src/worker/worker.ts
> +      return `//# sourceMappingURL=${newPath}`;
```suggestion
      return `//# sourceMappingURL=${this.rewritePath(path, false)}`);
```

2023-12-19 08:36 UTC, jason-ha commented on src/worker/worker.ts
> +    json.file = newPath;
can also just use `rewritePath` here.

2023-12-19 08:48 UTC, jason-ha commented on src/worker/worker.ts
> +                dtsExtName: this.data.dtsExtName ?? DTS_EXT,
I think you want `||`. That way empty string uses DTS_EXT.

2023-12-19 08:54 UTC, jason-ha commented on src/worker/worker.ts
> +  private rewritePath(path: string, ignoreDts: boolean): string {
I am not a huge fan of defaults, but I like flat boolean parameters less. (You can't see the argument at the call site.) 
So, I would make ignoreDts optional and not pass `false` at all of the regular uses.
There is a comment at the special case, but I admit I don't know why it is special after reading the comment. Lingering thoughts of why?

2023-12-19 08:57 UTC, jason-ha commented on src/worker/worker.ts
> +    return trimSuffix(path, DTS_EXT) + this.getDtsExtension();
`.data.dtsExtName` doesn't work here like it `.data.extname` works for `getJSPath`?

2023-12-19 09:01 UTC, jason-ha commented on src/worker/worker.ts
> +      // When reading paths, we don't want to rewrite the paths to DTS files, so we pass true to ignoreDts
Why don't we want to rewrite them like we would for .js? Can you add a little more commentary? Thanks!

2023-12-19 09:28 UTC, jason-ha commented on src/worker/worker.ts
> +                system: this.system,
tsc-multi is forking processes to handle builds. The options are passed from parent process to child via stdin.
The missing piece is to add `extDtsName` to `build.ts` lines 106 and 117. That is where extname is promoted from target option to general. All non-promoted keys are left in target per line 106.

2023-12-19 09:30 UTC, jason-ha requested changes
I did not review the big cloned file. I think I'd get lost without seeing diff.
Otherwise, I have a few suggestions but didn't find anything problematic.

Do be sure to update the Feature expected but not included portion of description.

2023-12-19 18:07 UTC, tylerbutler commented on src/worker/entry.ts
>    debug("Target", data.target);
```suggestion
  const data = await loadWorkerData();
  // It's a mystery to me, but the extname property is loaded in loadWorkerData, but dtsExtName is undefined.
  // However, it's defined in the target property, so we set it explicitly here.
  data.dtsExtName = data.target.dtsExtName as string;
  debug("Target", data.target);
```

2023-12-19 18:13 UTC, jason-ha commented on src/worker/entry.ts
>    debug("Target", data.target);
See https://github.com/tylerbutler/tsc-multi/pull/1#discussion_r1431139832

2023-12-19 18:23 UTC, tylerbutler commented on src/worker/worker.ts
> +    return trimSuffix(path, DTS_EXT) + this.getDtsExtension();
Good point. the getDtsExtension is no longer needed. I originally had some central logging there but removed it after debugging.

2023-12-19 18:37 UTC, tylerbutler commented on src/worker/worker.ts
> +  private rewritePath(path: string, ignoreDts: boolean): string {
Updated to have a default value `false`. I don't understand why it's a special case, but I can at least add details about what happens when we rewrite in the read function. I'll do another test and add those details.

2023-12-19 18:39 UTC, tylerbutler commented on src/worker/worker.ts
> +  private rewritePath(path: string, ignoreDts: boolean): string {
One drawback to default false is that it changes the logic even when not "opted in" to dts rewriting. That said, if they're not opted in, then all the dts extensions should be unchanged, so even though the codepaths are different the end result should be the same.

2023-12-19 18:57 UTC, tylerbutler commented on src/worker/worker.ts
> +                system: this.system,
Thank you! I completely missed that.

2023-12-19 19:05 UTC, tylerbutler commented on src/worker/worker.ts
> +      // When reading paths, we don't want to rewrite the paths to DTS files, so we pass true to ignoreDts
I added some more comments. If we rewrite the paths, there are errors like this:

error during command 'tsc-multi --config ../../../common/build/build-common/tsc-multi.esm.json' (exit code 1)
[mjs]: error TS6053: File '/home/tylerbu/code/release-1/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/lib.dom.d.ts' not found.
  The file is in the program because:
    Library 'lib.dom.d.ts' specified in compilerOptions
[mjs]: error TS6053: File '/home/tylerbu/code/release-1/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/lib.dom.iterable.d.ts' not found.
  The file is in the program because:
    Library 'lib.dom.iterable.d.ts' specified in compilerOptions
[mjs]: error TS6053: File '/home/tylerbu/code/release-1/node_modules/.pnpm/typescript@5.1.6/node_modules/typescript/lib/lib.es2020.d.ts' not found.
  The file is in the program because:
    Library 'lib.es2020.d.ts' specified in compilerOptions
[mjs]: error TS2318: Cannot find global type 'Array'.
[mjs]: error TS2318: Cannot find global type 'Boolean'.
[mjs]: error TS2318: Cannot find global type 'CallableFunction'.
[mjs]: error TS2318: Cannot find global type 'Function'.
[mjs]: error TS2318: Cannot find global type 'IArguments'.
[mjs]: error TS2318: Cannot find global type 'NewableFunction'.
[mjs]: error TS2318: Cannot find global type 'Number'.
[mjs]: error TS2318: Cannot find global type 'Object'.
[mjs]: error TS2318: Cannot find global type 'RegExp'.
[mjs]: error TS2318: Cannot find global type 'String'.
[mjs]: Found 13 errors.

I think that what's happening is that the build process uses the provided read method to read built-in types, so when we rewrite their paths, TypeScript later can't find them looking at the rewritten paths. That's just a guess though.

2023-12-19 21:39 UTC, jason-ha approved these changes
LGTM (split file caveat for review remains)

2024-02-10 01:56 UTC, tylerbutler commented
@jason-ha I realized this pr includes changes not yet in fluid framework main. I think commit 486ad76f588aa709c2657ee4b8c01cf0ad390026 is what's currently in main.

2024-06-06 23:17 UTC, closed without merging